# Generated by Django 4.0.4 on 2022-05-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectCore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_logo',
            field=models.ImageField(blank=True, default='', upload_to='recipes/logos'),
        ),
    ]
